-- 관리자 계정
INSERT INTO MEMBER (MID, MNICK, MPW, MDATE, MCONSENT) VALUES('admin@wanted.com','user0001','1111',SYSDATE,1);
COMMIT;
-- 추가계정 2개
INSERT INTO MEMBER (MID, MNICK, MPW, MDATE, MCONSENT) VALUES('ejkim@wanted.com','user0002','1111',SYSDATE,1);
INSERT INTO MEMBER (MID, MNICK, MPW, MDATE, MCONSENT) VALUES('becky@wanted.com','user0003','1111',SYSDATE,1);
COMMIT;