DROP TABLE "IFILE";
DROP TABLE "INQUIRY";
DROP TABLE "INQUIRY_CATEGORY";
DROP TABLE "COMMENT";
DROP TABLE "MEMBER";
DROP TABLE "POSTING";


CREATE TABLE "POSTING" (
	"wantedAuthNo"	VARCHAR2(50)		NOT NULL,
	"company"	VARCHAR2(100)		NULL,
	"title"	VARCHAR2(1000)		NULL,
	"sal"	VARCHAR2(50)		NULL,
	"minSal"	VARCHAR2(30)		NULL,
	"maxSal"	VARCHAR2(30)		NULL,
	"region"	VARCHAR2(30)		NULL,
	"holidayTpNm"	VARCHAR2(30)		NULL,
	"career"	VARCHAR2(30)		NULL,
	"regDt"	VARCHAR2(30)		NULL,
	"closeDt"	VARCHAR2(30)		NULL,
	"basicAddr"	VARCHAR2(100)		NULL,
	"detailAddr"	VARCHAR2(100)		NULL,
	"jobsCd"	VARCHAR2(30)		NULL
);

ALTER TABLE "POSTING" ADD CONSTRAINT "PK_POSTING" PRIMARY KEY (
	"wantedAuthNo"
);


CREATE TABLE "MEMBER" (
	"MID"	VARCHAR2(100)		NOT NULL,
	"MPW"	VARCHAR2(20)		NOT NULL,
	"MNAME"	VARCHAR2(30)		NOT NULL,
	"MDATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MCONSENT"	NUMBER(3)	DEFAULT 0	NOT NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MID"
);

COMMENT ON COLUMN "MEMBER"."MID" IS '@';

COMMENT ON COLUMN "MEMBER"."MPW" IS '영문숫자!@^_최소6자이상';

COMMENT ON COLUMN "MEMBER"."MCONSENT" IS '선택1=1., 선택2=2, 선택12=3, 선택3=4, 선택123=7';


CREATE TABLE "COMMENT" (
	"CTIME"	TIMESTAMP		NOT NULL,
	"CCONTENT"	VARCHAR2(300)		NOT NULL,
	"MID"	VARCHAR2(100)		NOT NULL,
	"wantedAuthNo"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."MID" IS '@';


CREATE TABLE "INQUIRY_CATEGORY" (
	"ICATEGORY"	CHAR(1)		NOT NULL,
	"ICATEGORYNAME"	VARCHAR2(50)		NOT NULL
);

ALTER TABLE "INQUIRY_CATEGORY" ADD CONSTRAINT "PK_INQUIRY_CATEGORY" PRIMARY KEY (
	"ICATEGORY"
);

COMMENT ON COLUMN "INQUIRY_CATEGORY"."ICATEGORY" IS '7종류';


CREATE TABLE "INQUIRY" (
	"INO"	NUMBER		NOT NULL,
	"ICONTENT"	VARCHAR2(4000)		NOT NULL,
	"IDATE"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP	NOT NULL,
	"MID"	VARCHAR2(100)		NOT NULL,
	"ICATEGORY"	CHAR(1)		NOT NULL
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "PK_INQUIRY" PRIMARY KEY (
	"INO"
);

COMMENT ON COLUMN "INQUIRY"."MID" IS '@';

COMMENT ON COLUMN "INQUIRY"."ICATEGORY" IS '7종류';


CREATE TABLE "IFILE" (
	"IFILEPATH"	VARCHAR2(500)		NOT NULL,
	"INO"	NUMBER		NOT NULL
);

ALTER TABLE "IFILE" ADD CONSTRAINT "PK_IFILE" PRIMARY KEY (
	"IFILEPATH"
);

COMMENT ON COLUMN "IFILE"."IFILEPATH" IS '/resources/inquiry';


--참조키 설정

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_POSTING_TO_COMMENT_1" FOREIGN KEY (
	"wantedAuthNo"
)
REFERENCES "POSTING" (
	"wantedAuthNo"
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "FK_MEMBER_TO_INQUIRY_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "FK_INQ_CATE_TO_INQ_1" FOREIGN KEY (
	"ICATEGORY"
)
REFERENCES "INQUIRY_CATEGORY" (
	"ICATEGORY"
);

ALTER TABLE "IFILE" ADD CONSTRAINT "FK_INQUIRY_TO_IFILE_1" FOREIGN KEY (
	"INO"
)
REFERENCES "INQUIRY" (
	"INO"
);
