DROP TABLE "INQUIRY";
DROP TABLE "COMMENT";
DROP TABLE "MEMBER";
DROP TABLE "POSTING";


CREATE TABLE "POSTING" (
	"wantedAuthNo"	VARCHAR2(50)		NOT NULL,
	"company"	VARCHAR2(100)		NULL,
	"title"	VARCHAR2(1000)		NULL,
	"salTpNm"	VARCHAR2(10)		NULL,
	"sal"	VARCHAR2(50)		NULL,
	"region"	VARCHAR2(30)		NULL,
	"minEdubg"	VARCHAR2(30)		NULL,
	"career"	VARCHAR2(30)		NULL,
	"regDt"	VARCHAR2(30)		NULL,
	"closeDt"	VARCHAR2(30)		NULL,
	"basicAddr"	VARCHAR2(100)		NULL,
	"jobsCd"	VARCHAR2(30)		NULL
);

ALTER TABLE "POSTING" ADD CONSTRAINT "PK_POSTING" PRIMARY KEY (
	"wantedAuthNo"
);


CREATE TABLE "MEMBER" (
	"MID"	VARCHAR2(100)		NOT NULL,
	"MPW"	VARCHAR2(20)		NOT NULL,
    "MCONSENT" VARCHAR2(1)  NOT NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MID"
);

COMMENT ON COLUMN "MEMBER"."MID" IS '@';

COMMENT ON COLUMN "MEMBER"."MPW" IS '영문숫자!@^_최소6자이상';


CREATE TABLE "COMMENT" (
	"CTIME"	TIMESTAMP		NOT NULL,
	"CCONTENT"	VARCHAR2(300)		NOT NULL,
	"MID"	VARCHAR2(100)		NOT NULL,
	"wantedAuthNo"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."MID" IS '@';



CREATE TABLE "INQUIRY" (
	"INO"	NUMBER		NOT NULL,
    "ITITLE" VARCHAR2(100)  NULL,
	"ICONTENT"	VARCHAR2(4000)		NULL,
	"IDATE"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP NULL,
    "IHIT" NUMBER NULL,
	"MID"	VARCHAR2(100)		NOT NULL
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "PK_INQUIRY" PRIMARY KEY (
	"INO"
);

COMMENT ON COLUMN "INQUIRY"."MID" IS '@';


--참조키 설정

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_POSTING_TO_COMMENT_1" FOREIGN KEY (
	"wantedAuthNo"
)
REFERENCES "POSTING" (
	"wantedAuthNo"
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "FK_MEMBER_TO_INQUIRY_1" FOREIGN KEY (
	"MID"
)
REFERENCES "MEMBER" (
	"MID"
);